project:
  type: website
  output-dir: docs
  render: 
    - index.qmd
    - syllabus.qmd
    - homework/*.qmd
    - slides/*.qmd
    - exams/midterm.qmd
    - exams/2023-final-exam/index.qmd
website:
  title: "Stat 151"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: https://srvanderplas.github.io/stat-computing-r-python/
        text: Textbook
      - href: syllabus.pdf
        text: Syllabus
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
