project:
  type: website
  output-dir: docs
  pre-render:
    - scripts/update-assignment-dates.R
    - scripts/hide-future-assignments.R
  render:
    - index.qmd
    - syllabus.qmd
    - homework/*.qmd
    - project/*.qmd
    - slides/*.qmd
    - exams/*.qmd

website:
  title: "Stat 151"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: https://srvanderplas.github.io/stat-computing-r-python/
        text: Textbook
      - href: syllabus.pdf
        text: Syllabus
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
