on:
  schedule:
    - cron: "0 0 * * 0,3,5"
  push:
    branches: main

name: Render and Publish

# you need these permissions to publish to GitHub pages
# permissions:
#     contents: write
#     pages: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GH_TOKEN }}

      - name: Set RENV_PATHS_ROOT
        shell: bash
        run: |
          echo "RENV_PATHS_ROOT=${{ runner.temp }}/renv" >> $GITHUB_ENV
    
      # https://jasonraimondi.com/posts/install-google-fonts-in-github-workflow/
      - name: Install Google Fonts
        run: |
          wget -O Noto_Sans.zip https://fonts.google.com/download?family=Noto%20Sans
          unzip -d Noto_Sans/ Noto_Sans.zip
          mv Noto_Sans /usr/share/fonts/
          fc-cache -fv

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          # To install LaTeX to build PDF book
          tinytex: true

      # add software dependencies here and any libraries

      # From https://github.com/actions/setup-python
      - name: Setup Python
        uses: actions/setup-python@v3

      # From https://github.com/r-lib/actions/tree/v2-branch/setup-r
      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install ubuntu dependencies
        run: |
          sudo add-apt-repository ppa:ubuntugis/ppa
          sudo add-apt-repository ppa:c2d4u.team/c2d4u4.0+
          sudo apt update
          sudo apt install libudunits2-dev \
                           libcurl4-openssl-dev \
                           libgdal-dev \
                           gdal-bin \
                           libproj-dev \
                           libharfbuzz-dev \
                           libfribidi-dev
          sudo apt install r-cran-sf r-cran-rnaturalearthdata r-cran-terra

      - name: Install and activate renv
        run: |
          install.packages("renv")
          renv::activate()
        shell: Rscript {0}
        
      - name: Get R and OS version
        id: get-version
        run: |
          cat("##[set-output name=os-version;]", sessionInfo()$running, "\n", sep = "")
          cat("##[set-output name=r-version;]", R.Version()$version.string, sep = "")
        shell: Rscript {0}
        
      - name: Restore Renv package cache
        uses: actions/cache@v3
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ steps.get-version.outputs.os-version }}-${{ steps.get-version.outputs.r-version }}-${{ inputs.cache-version }}-${{ hashFiles('renv.lock') }}
          restore-keys: ${{ steps.get-version.outputs.os-version }}-${{ steps.get-version.outputs.r-version }}-${{inputs.cache-version }}-
          
      - name: Setup renv
        uses: r-lib/actions/setup-renv@v2

      # See more at https://github.com/quarto-dev/quarto-actions/blob/main/examples/example-03-dependencies.md
      
      - name: Cache renv packages
        uses: actions/cache@v1
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Install Python dependencies
        run: |
          pip install pandas datetime seaborn matplotlib

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2

      # Note: If Publishing to GitHub Pages, set the permissions correctly
      
      - name: Publish to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} # this secret is always available for github actions
        run: |
          git config --global user.email "svanderplas2@unl.edu"
          git config --global user.name "Auto Build 251 Site"
          quarto publish gh-pages docs --no-render --no-browser
